spring:
  application:
    name: dome-adapter
  main:
    web-application-type: reactive
  webflux:
    base-path: ${APP_CONTEXT_PATH:/vci}
  r2dbc:
    url: ${SPRING_R2DBC_URL:}
    username: ${SPRING_R2DBC_USERNAME:}
    password: ${SPRING_R2DBC_PASSWORD:}
  flyway:
    url: ${SPRING_FLYWAY_URL:}
    user: ${SPRING_R2DBC_USERNAME:}
    password: ${SPRING_R2DBC_PASSWORD:}
    locations: classpath:db/migration
    default-schema: ${SPRING_FLYWAY_DEFAULT_SCHEMA:dome_adapter}
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS:false}
          ssl:
            enable: ${SMTP_SSL_ENABLE:true}
            trust: ${SMTP_SSL_TRUST:}
  messages:
    basename: messages/messages
  config:
    import: optional:file:${ADAPTER_LOCALFILES_SECRETS:}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.altia.domeadapter: ${LOGGING_LEVEL_ES_ALTIA_DOMEADAPTER:INFO}
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus
      base-path: /
      path-mapping:
        health: health
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true

springdoc:
  api-docs:
    path: /springdoc/api-docs
  swagger-ui:
    path: /springdoc/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

app:
  verifier-url: ${APP_VERIFIER_URL:}
  issuer-url: ${APP_ISSUER_URL:}
  default-lang: ${APP_DEFAULT_LANG:en}
  config-source: ${APP_CONFIG_SOURCE:yaml}
  dome-adapter-enabled: ${DOME_ADAPTER_ENABLED:false}
  mail:
    from: ${APP_MAIL_FROM:no-reply@example.com}

adapter-identity:
  credential-subject-did-key: ${ADAPTER_IDENTITY_CREDENTIAL_SUBJECT_DID_KEY:}
  crypto:
    private-key: ${ADAPTER_IDENTITY_CRYPTO_PRIVATE_KEY:}

cors:
  external-allowed-origins: ${CORS_EXTERNAL_ALLOWED_ORIGINS:}

retry:
  label-upload:
    certifier-email: ${RETRY_LABEL_UPLOAD_CERTIFIER_EMAIL:}
    marketplace-email: ${RETRY_LABEL_UPLOAD_MARKETPLACE_EMAIL:}